name:                codeEditor
version:             0.1.0.0
homepage:            https://github.com/simmihugs/codeEditor#readme
license:             BSD3
author:              Simon Graetz
maintainer:          simon.graetz@gmx.de
copyright:           2022 Simon Graetz

extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - data-default
  - lens
  - monomer
  - text
  - text-show
  - containers
  - ghc-syntax-highlighter

library:
  source-dirs: src

executables:
  app:
    main:          Main.hs
    source-dirs:   app
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
    dependencies:
    - codeEditor
