name:                monomer-textArea
version:             0.1.0.0
homepage:            https://github.com/simmihugs/monomer-textArea#readme
license:             BSD3
author:              Simon Graetz
maintainer:          simon.graetz@gmx.de
copyright:           2022 Simon Graetz
extra-source-files:
- README.md

default-extensions:
- OverloadedStrings

dependencies:
  - base >= 4.7 && < 5
  - data-default
  - lens
  - monomer
  - text
  - text-show
  - containers
  - ghc-syntax-highlighter

library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns

executables:
  app:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -fwarn-incomplete-patterns
    - -threaded
